// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: oll/common.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shared structured-log severity used by host and plugin records.
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_TRACE       LogLevel = 1
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 2
	LogLevel_LOG_LEVEL_INFO        LogLevel = 3
	LogLevel_LOG_LEVEL_WARN        LogLevel = 4
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_TRACE",
		2: "LOG_LEVEL_DEBUG",
		3: "LOG_LEVEL_INFO",
		4: "LOG_LEVEL_WARN",
		5: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_TRACE":       1,
		"LOG_LEVEL_DEBUG":       2,
		"LOG_LEVEL_INFO":        3,
		"LOG_LEVEL_WARN":        4,
		"LOG_LEVEL_ERROR":       5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_oll_common_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_oll_common_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED           ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT      ErrorCode = 1
	ErrorCode_ERROR_CODE_NOT_FOUND             ErrorCode = 2
	ErrorCode_ERROR_CODE_ALREADY_EXISTS        ErrorCode = 3
	ErrorCode_ERROR_CODE_REVISION_CONFLICT     ErrorCode = 4
	ErrorCode_ERROR_CODE_CALL_DEPTH_EXCEEDED   ErrorCode = 5
	ErrorCode_ERROR_CODE_CAUSAL_DEPTH_EXCEEDED ErrorCode = 6
	ErrorCode_ERROR_CODE_DEADLINE_EXCEEDED     ErrorCode = 7
	ErrorCode_ERROR_CODE_CANCELLED             ErrorCode = 8
	ErrorCode_ERROR_CODE_UNAVAILABLE           ErrorCode = 9
	ErrorCode_ERROR_CODE_PROTOCOL_MISMATCH     ErrorCode = 10
	ErrorCode_ERROR_CODE_FAILED_PRECONDITION   ErrorCode = 11
	ErrorCode_ERROR_CODE_INTERNAL              ErrorCode = 12
	ErrorCode_ERROR_CODE_PAYLOAD_TOO_LARGE     ErrorCode = 13
	ErrorCode_ERROR_CODE_UNSUPPORTED           ErrorCode = 14
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_INVALID_ARGUMENT",
		2:  "ERROR_CODE_NOT_FOUND",
		3:  "ERROR_CODE_ALREADY_EXISTS",
		4:  "ERROR_CODE_REVISION_CONFLICT",
		5:  "ERROR_CODE_CALL_DEPTH_EXCEEDED",
		6:  "ERROR_CODE_CAUSAL_DEPTH_EXCEEDED",
		7:  "ERROR_CODE_DEADLINE_EXCEEDED",
		8:  "ERROR_CODE_CANCELLED",
		9:  "ERROR_CODE_UNAVAILABLE",
		10: "ERROR_CODE_PROTOCOL_MISMATCH",
		11: "ERROR_CODE_FAILED_PRECONDITION",
		12: "ERROR_CODE_INTERNAL",
		13: "ERROR_CODE_PAYLOAD_TOO_LARGE",
		14: "ERROR_CODE_UNSUPPORTED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":           0,
		"ERROR_CODE_INVALID_ARGUMENT":      1,
		"ERROR_CODE_NOT_FOUND":             2,
		"ERROR_CODE_ALREADY_EXISTS":        3,
		"ERROR_CODE_REVISION_CONFLICT":     4,
		"ERROR_CODE_CALL_DEPTH_EXCEEDED":   5,
		"ERROR_CODE_CAUSAL_DEPTH_EXCEEDED": 6,
		"ERROR_CODE_DEADLINE_EXCEEDED":     7,
		"ERROR_CODE_CANCELLED":             8,
		"ERROR_CODE_UNAVAILABLE":           9,
		"ERROR_CODE_PROTOCOL_MISMATCH":     10,
		"ERROR_CODE_FAILED_PRECONDITION":   11,
		"ERROR_CODE_INTERNAL":              12,
		"ERROR_CODE_PAYLOAD_TOO_LARGE":     13,
		"ERROR_CODE_UNSUPPORTED":           14,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_oll_common_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_oll_common_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{1}
}

// Node IDs are canonical UUID v4 strings. They identify a node but do not carry
// routing, authority, or other application semantics.
type NodeId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeId) Reset() {
	*x = NodeId{}
	mi := &file_oll_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeId) ProtoMessage() {}

func (x *NodeId) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeId.ProtoReflect.Descriptor instead.
func (*NodeId) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{0}
}

func (x *NodeId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// A durable human-facing node name. Implementations validate the lowercase
// DNS-label syntax documented in architecture.md.
type NodeName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeName) Reset() {
	*x = NodeName{}
	mi := &file_oll_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeName) ProtoMessage() {}

func (x *NodeName) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeName.ProtoReflect.Descriptor instead.
func (*NodeName) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{1}
}

func (x *NodeName) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// NodeId and NodeName are both required and have a durable one-to-one
// relationship. A node presents this same pair at every local and remote
// protocol boundary.
type NodeIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        *NodeId                `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      *NodeName              `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_oll_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{2}
}

func (x *NodeIdentity) GetNodeId() *NodeId {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *NodeIdentity) GetNodeName() *NodeName {
	if x != nil {
		return x.NodeName
	}
	return nil
}

type ReplicaId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaId) Reset() {
	*x = ReplicaId{}
	mi := &file_oll_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaId) ProtoMessage() {}

func (x *ReplicaId) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaId.ProtoReflect.Descriptor instead.
func (*ReplicaId) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicaId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DocumentId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentId) Reset() {
	*x = DocumentId{}
	mi := &file_oll_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentId) ProtoMessage() {}

func (x *DocumentId) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentId.ProtoReflect.Descriptor instead.
func (*DocumentId) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CatalogNodeId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogNodeId) Reset() {
	*x = CatalogNodeId{}
	mi := &file_oll_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogNodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogNodeId) ProtoMessage() {}

func (x *CatalogNodeId) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogNodeId.ProtoReflect.Descriptor instead.
func (*CatalogNodeId) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{5}
}

func (x *CatalogNodeId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BinaryId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryId) Reset() {
	*x = BinaryId{}
	mi := &file_oll_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryId) ProtoMessage() {}

func (x *BinaryId) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryId.ProtoReflect.Descriptor instead.
func (*BinaryId) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{6}
}

func (x *BinaryId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Immutable publisher identity used for package, process, job, and filesystem
// ownership. Its dotted path-safe grammar is defined in plugin-storage.md.
type PluginId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginId) Reset() {
	*x = PluginId{}
	mi := &file_oll_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginId) ProtoMessage() {}

func (x *PluginId) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginId.ProtoReflect.Descriptor instead.
func (*PluginId) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{7}
}

func (x *PluginId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Mutable unique human-facing selector. Changing it never changes PluginId or
// moves PluginId-keyed storage.
type PluginName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginName) Reset() {
	*x = PluginName{}
	mi := &file_oll_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginName) ProtoMessage() {}

func (x *PluginName) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginName.ProtoReflect.Descriptor instead.
func (*PluginName) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{8}
}

func (x *PluginName) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Host-generated canonical UUID v4 for one asynchronous plugin job.
type PluginJobId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginJobId) Reset() {
	*x = PluginJobId{}
	mi := &file_oll_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginJobId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginJobId) ProtoMessage() {}

func (x *PluginJobId) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginJobId.ProtoReflect.Descriptor instead.
func (*PluginJobId) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{9}
}

func (x *PluginJobId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Plugin-generated canonical UUID v4, unique within the deployment, for one
// verified artifact transfer and result.
type PluginArtifactId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginArtifactId) Reset() {
	*x = PluginArtifactId{}
	mi := &file_oll_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginArtifactId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginArtifactId) ProtoMessage() {}

func (x *PluginArtifactId) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginArtifactId.ProtoReflect.Descriptor instead.
func (*PluginArtifactId) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{10}
}

func (x *PluginArtifactId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CatalogRevision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An opaque token representing the observed catalog state of one
	// CatalogNodeId. This intentionally does not expose Loro's frontier or
	// version-vector API.
	Token         []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogRevision) Reset() {
	*x = CatalogRevision{}
	mi := &file_oll_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogRevision) ProtoMessage() {}

func (x *CatalogRevision) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogRevision.ProtoReflect.Descriptor instead.
func (*CatalogRevision) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{11}
}

func (x *CatalogRevision) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type DocumentRevision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An opaque token representing the observed content and abstract CRDT state
	// of one DocumentId. This intentionally does not expose Loro's frontier or
	// version-vector API.
	Token         []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRevision) Reset() {
	*x = DocumentRevision{}
	mi := &file_oll_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRevision) ProtoMessage() {}

func (x *DocumentRevision) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRevision.ProtoReflect.Descriptor instead.
func (*DocumentRevision) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{12}
}

func (x *DocumentRevision) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type TraceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ParentCallId  *uint64                `protobuf:"varint,2,opt,name=parent_call_id,json=parentCallId,proto3,oneof" json:"parent_call_id,omitempty"`
	CallDepth     uint32                 `protobuf:"varint,3,opt,name=call_depth,json=callDepth,proto3" json:"call_depth,omitempty"`
	CausalDepth   uint32                 `protobuf:"varint,4,opt,name=causal_depth,json=causalDepth,proto3" json:"causal_depth,omitempty"`
	TaskId        *string                `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
	TaskGroupId   *string                `protobuf:"bytes,6,opt,name=task_group_id,json=taskGroupId,proto3,oneof" json:"task_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceContext) Reset() {
	*x = TraceContext{}
	mi := &file_oll_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceContext) ProtoMessage() {}

func (x *TraceContext) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceContext.ProtoReflect.Descriptor instead.
func (*TraceContext) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{13}
}

func (x *TraceContext) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TraceContext) GetParentCallId() uint64 {
	if x != nil && x.ParentCallId != nil {
		return *x.ParentCallId
	}
	return 0
}

func (x *TraceContext) GetCallDepth() uint32 {
	if x != nil {
		return x.CallDepth
	}
	return 0
}

func (x *TraceContext) GetCausalDepth() uint32 {
	if x != nil {
		return x.CausalDepth
	}
	return 0
}

func (x *TraceContext) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *TraceContext) GetTaskGroupId() string {
	if x != nil && x.TaskGroupId != nil {
		return *x.TaskGroupId
	}
	return ""
}

type ProtocolError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=oll.protocol.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Details       []*anypb.Any           `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolError) Reset() {
	*x = ProtocolError{}
	mi := &file_oll_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolError) ProtoMessage() {}

func (x *ProtocolError) ProtoReflect() protoreflect.Message {
	mi := &file_oll_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolError.ProtoReflect.Descriptor instead.
func (*ProtocolError) Descriptor() ([]byte, []int) {
	return file_oll_common_proto_rawDescGZIP(), []int{14}
}

func (x *ProtocolError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ProtocolError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProtocolError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ProtocolError) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProtocolError) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_oll_common_proto protoreflect.FileDescriptor

const file_oll_common_proto_rawDesc = "" +
	"\n" +
	"\x10oll/common.proto\x12\foll.protocol\x1a\x19google/protobuf/any.proto\"\x1e\n" +
	"\x06NodeId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\" \n" +
	"\bNodeName\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"r\n" +
	"\fNodeIdentity\x12-\n" +
	"\anode_id\x18\x01 \x01(\v2\x14.oll.protocol.NodeIdR\x06nodeId\x123\n" +
	"\tnode_name\x18\x02 \x01(\v2\x16.oll.protocol.NodeNameR\bnodeName\"!\n" +
	"\tReplicaId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\"\n" +
	"\n" +
	"DocumentId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"%\n" +
	"\rCatalogNodeId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\" \n" +
	"\bBinaryId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\" \n" +
	"\bPluginId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\"\n" +
	"\n" +
	"PluginName\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"#\n" +
	"\vPluginJobId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"(\n" +
	"\x10PluginArtifactId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"'\n" +
	"\x0fCatalogRevision\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"(\n" +
	"\x10DocumentRevision\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"\x9a\x02\n" +
	"\fTraceContext\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12)\n" +
	"\x0eparent_call_id\x18\x02 \x01(\x04H\x00R\fparentCallId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"call_depth\x18\x03 \x01(\rR\tcallDepth\x12!\n" +
	"\fcausal_depth\x18\x04 \x01(\rR\vcausalDepth\x12\x1c\n" +
	"\atask_id\x18\x05 \x01(\tH\x01R\x06taskId\x88\x01\x01\x12'\n" +
	"\rtask_group_id\x18\x06 \x01(\tH\x02R\vtaskGroupId\x88\x01\x01B\x11\n" +
	"\x0f_parent_call_idB\n" +
	"\n" +
	"\b_task_idB\x10\n" +
	"\x0e_task_group_id\"\xa8\x02\n" +
	"\rProtocolError\x12+\n" +
	"\x04code\x18\x01 \x01(\x0e2\x17.oll.protocol.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12E\n" +
	"\bmetadata\x18\x04 \x03(\v2).oll.protocol.ProtocolError.MetadataEntryR\bmetadata\x12.\n" +
	"\adetails\x18\x05 \x03(\v2\x14.google.protobuf.AnyR\adetails\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x8c\x01\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_TRACE\x10\x01\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x03\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x04\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x05*\xe2\x03\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\x03\x12 \n" +
	"\x1cERROR_CODE_REVISION_CONFLICT\x10\x04\x12\"\n" +
	"\x1eERROR_CODE_CALL_DEPTH_EXCEEDED\x10\x05\x12$\n" +
	" ERROR_CODE_CAUSAL_DEPTH_EXCEEDED\x10\x06\x12 \n" +
	"\x1cERROR_CODE_DEADLINE_EXCEEDED\x10\a\x12\x18\n" +
	"\x14ERROR_CODE_CANCELLED\x10\b\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\t\x12 \n" +
	"\x1cERROR_CODE_PROTOCOL_MISMATCH\x10\n" +
	"\x12\"\n" +
	"\x1eERROR_CODE_FAILED_PRECONDITION\x10\v\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\f\x12 \n" +
	"\x1cERROR_CODE_PAYLOAD_TOO_LARGE\x10\r\x12\x1a\n" +
	"\x16ERROR_CODE_UNSUPPORTED\x10\x0eb\x06proto3"

var (
	file_oll_common_proto_rawDescOnce sync.Once
	file_oll_common_proto_rawDescData []byte
)

func file_oll_common_proto_rawDescGZIP() []byte {
	file_oll_common_proto_rawDescOnce.Do(func() {
		file_oll_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oll_common_proto_rawDesc), len(file_oll_common_proto_rawDesc)))
	})
	return file_oll_common_proto_rawDescData
}

var file_oll_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_oll_common_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_oll_common_proto_goTypes = []any{
	(LogLevel)(0),            // 0: oll.protocol.LogLevel
	(ErrorCode)(0),           // 1: oll.protocol.ErrorCode
	(*NodeId)(nil),           // 2: oll.protocol.NodeId
	(*NodeName)(nil),         // 3: oll.protocol.NodeName
	(*NodeIdentity)(nil),     // 4: oll.protocol.NodeIdentity
	(*ReplicaId)(nil),        // 5: oll.protocol.ReplicaId
	(*DocumentId)(nil),       // 6: oll.protocol.DocumentId
	(*CatalogNodeId)(nil),    // 7: oll.protocol.CatalogNodeId
	(*BinaryId)(nil),         // 8: oll.protocol.BinaryId
	(*PluginId)(nil),         // 9: oll.protocol.PluginId
	(*PluginName)(nil),       // 10: oll.protocol.PluginName
	(*PluginJobId)(nil),      // 11: oll.protocol.PluginJobId
	(*PluginArtifactId)(nil), // 12: oll.protocol.PluginArtifactId
	(*CatalogRevision)(nil),  // 13: oll.protocol.CatalogRevision
	(*DocumentRevision)(nil), // 14: oll.protocol.DocumentRevision
	(*TraceContext)(nil),     // 15: oll.protocol.TraceContext
	(*ProtocolError)(nil),    // 16: oll.protocol.ProtocolError
	nil,                      // 17: oll.protocol.ProtocolError.MetadataEntry
	(*anypb.Any)(nil),        // 18: google.protobuf.Any
}
var file_oll_common_proto_depIdxs = []int32{
	2,  // 0: oll.protocol.NodeIdentity.node_id:type_name -> oll.protocol.NodeId
	3,  // 1: oll.protocol.NodeIdentity.node_name:type_name -> oll.protocol.NodeName
	1,  // 2: oll.protocol.ProtocolError.code:type_name -> oll.protocol.ErrorCode
	17, // 3: oll.protocol.ProtocolError.metadata:type_name -> oll.protocol.ProtocolError.MetadataEntry
	18, // 4: oll.protocol.ProtocolError.details:type_name -> google.protobuf.Any
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_oll_common_proto_init() }
func file_oll_common_proto_init() {
	if File_oll_common_proto != nil {
		return
	}
	file_oll_common_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oll_common_proto_rawDesc), len(file_oll_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oll_common_proto_goTypes,
		DependencyIndexes: file_oll_common_proto_depIdxs,
		EnumInfos:         file_oll_common_proto_enumTypes,
		MessageInfos:      file_oll_common_proto_msgTypes,
	}.Build()
	File_oll_common_proto = out.File
	file_oll_common_proto_goTypes = nil
	file_oll_common_proto_depIdxs = nil
}
