// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: oll/config.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A closure is never serialized. This is a session-scoped host-owned handle
// into oll's embedded configuration runtime; Lua does not call the plugin.
type ConfigFunctionRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FunctionId    string                 `protobuf:"bytes,2,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFunctionRef) Reset() {
	*x = ConfigFunctionRef{}
	mi := &file_oll_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFunctionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFunctionRef) ProtoMessage() {}

func (x *ConfigFunctionRef) ProtoReflect() protoreflect.Message {
	mi := &file_oll_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFunctionRef.ProtoReflect.Descriptor instead.
func (*ConfigFunctionRef) Descriptor() ([]byte, []int) {
	return file_oll_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigFunctionRef) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConfigFunctionRef) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

type ConfigList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ConfigValue         `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigList) Reset() {
	*x = ConfigList{}
	mi := &file_oll_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigList) ProtoMessage() {}

func (x *ConfigList) ProtoReflect() protoreflect.Message {
	mi := &file_oll_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigList.ProtoReflect.Descriptor instead.
func (*ConfigList) Descriptor() ([]byte, []int) {
	return file_oll_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigList) GetValues() []*ConfigValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConfigMap struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Entries       map[string]*ConfigValue `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMap) Reset() {
	*x = ConfigMap{}
	mi := &file_oll_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMap) ProtoMessage() {}

func (x *ConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_oll_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMap.ProtoReflect.Descriptor instead.
func (*ConfigMap) Descriptor() ([]byte, []int) {
	return file_oll_config_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigMap) GetEntries() map[string]*ConfigValue {
	if x != nil {
		return x.Entries
	}
	return nil
}

// The structured value format crossing the configuration boundary and used by
// Lua, structured results, and log fields. Generic plugin actions use
// shell-style string argv instead. Lua adapters must reject cyclic tables and
// values that cannot be represented here. A root value has depth zero and the
// deepest accepted value has depth 33. Numbers must be finite; Timestamp and
// Duration values must be inside their protobuf domains. Function handles are
// accepted only by configuration-function calls for the exact active session
// and an existing registry entry; durable values and log fields reject them.
type ConfigValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ConfigValue_NullValue
	//	*ConfigValue_BoolValue
	//	*ConfigValue_IntegerValue
	//	*ConfigValue_NumberValue
	//	*ConfigValue_StringValue
	//	*ConfigValue_BytesValue
	//	*ConfigValue_ListValue
	//	*ConfigValue_MapValue
	//	*ConfigValue_FunctionValue
	//	*ConfigValue_TimestampValue
	//	*ConfigValue_DurationValue
	Kind          isConfigValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValue) Reset() {
	*x = ConfigValue{}
	mi := &file_oll_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValue) ProtoMessage() {}

func (x *ConfigValue) ProtoReflect() protoreflect.Message {
	mi := &file_oll_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValue.ProtoReflect.Descriptor instead.
func (*ConfigValue) Descriptor() ([]byte, []int) {
	return file_oll_config_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigValue) GetKind() isConfigValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ConfigValue) GetNullValue() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_NullValue); ok {
			return x.NullValue
		}
	}
	return structpb.NullValue(0)
}

func (x *ConfigValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ConfigValue) GetIntegerValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return 0
}

func (x *ConfigValue) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *ConfigValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ConfigValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *ConfigValue) GetListValue() *ConfigList {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *ConfigValue) GetMapValue() *ConfigMap {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

func (x *ConfigValue) GetFunctionValue() *ConfigFunctionRef {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_FunctionValue); ok {
			return x.FunctionValue
		}
	}
	return nil
}

func (x *ConfigValue) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *ConfigValue) GetDurationValue() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Kind.(*ConfigValue_DurationValue); ok {
			return x.DurationValue
		}
	}
	return nil
}

type isConfigValue_Kind interface {
	isConfigValue_Kind()
}

type ConfigValue_NullValue struct {
	NullValue structpb.NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

type ConfigValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type ConfigValue_IntegerValue struct {
	IntegerValue int64 `protobuf:"zigzag64,3,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type ConfigValue_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,4,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type ConfigValue_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ConfigValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,6,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type ConfigValue_ListValue struct {
	ListValue *ConfigList `protobuf:"bytes,7,opt,name=list_value,json=listValue,proto3,oneof"`
}

type ConfigValue_MapValue struct {
	MapValue *ConfigMap `protobuf:"bytes,8,opt,name=map_value,json=mapValue,proto3,oneof"`
}

type ConfigValue_FunctionValue struct {
	FunctionValue *ConfigFunctionRef `protobuf:"bytes,9,opt,name=function_value,json=functionValue,proto3,oneof"`
}

type ConfigValue_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type ConfigValue_DurationValue struct {
	DurationValue *durationpb.Duration `protobuf:"bytes,11,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

func (*ConfigValue_NullValue) isConfigValue_Kind() {}

func (*ConfigValue_BoolValue) isConfigValue_Kind() {}

func (*ConfigValue_IntegerValue) isConfigValue_Kind() {}

func (*ConfigValue_NumberValue) isConfigValue_Kind() {}

func (*ConfigValue_StringValue) isConfigValue_Kind() {}

func (*ConfigValue_BytesValue) isConfigValue_Kind() {}

func (*ConfigValue_ListValue) isConfigValue_Kind() {}

func (*ConfigValue_MapValue) isConfigValue_Kind() {}

func (*ConfigValue_FunctionValue) isConfigValue_Kind() {}

func (*ConfigValue_TimestampValue) isConfigValue_Kind() {}

func (*ConfigValue_DurationValue) isConfigValue_Kind() {}

type ConfigPathSegment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ConfigPathSegment_Key
	//	*ConfigPathSegment_Index
	Kind          isConfigPathSegment_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPathSegment) Reset() {
	*x = ConfigPathSegment{}
	mi := &file_oll_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPathSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPathSegment) ProtoMessage() {}

func (x *ConfigPathSegment) ProtoReflect() protoreflect.Message {
	mi := &file_oll_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPathSegment.ProtoReflect.Descriptor instead.
func (*ConfigPathSegment) Descriptor() ([]byte, []int) {
	return file_oll_config_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigPathSegment) GetKind() isConfigPathSegment_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ConfigPathSegment) GetKey() string {
	if x != nil {
		if x, ok := x.Kind.(*ConfigPathSegment_Key); ok {
			return x.Key
		}
	}
	return ""
}

func (x *ConfigPathSegment) GetIndex() uint64 {
	if x != nil {
		if x, ok := x.Kind.(*ConfigPathSegment_Index); ok {
			return x.Index
		}
	}
	return 0
}

type isConfigPathSegment_Kind interface {
	isConfigPathSegment_Kind()
}

type ConfigPathSegment_Key struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3,oneof"`
}

type ConfigPathSegment_Index struct {
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3,oneof"`
}

func (*ConfigPathSegment_Key) isConfigPathSegment_Kind() {}

func (*ConfigPathSegment_Index) isConfigPathSegment_Kind() {}

// Relative to the caller's own live per-plugin Lua result. List indexes are
// zero-based at this language-neutral boundary.
type ConfigPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*ConfigPathSegment   `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPath) Reset() {
	*x = ConfigPath{}
	mi := &file_oll_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPath) ProtoMessage() {}

func (x *ConfigPath) ProtoReflect() protoreflect.Message {
	mi := &file_oll_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPath.ProtoReflect.Descriptor instead.
func (*ConfigPath) Descriptor() ([]byte, []int) {
	return file_oll_config_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigPath) GetSegments() []*ConfigPathSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *ConfigPath            `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_oll_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oll_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_oll_config_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigRequest) GetPath() *ConfigPath {
	if x != nil {
		return x.Path
	}
	return nil
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *ConfigValue           `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_oll_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oll_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_oll_config_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigResponse) GetValue() *ConfigValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type InvokeConfigFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *ConfigFunctionRef     `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Arguments     []*ConfigValue         `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeConfigFunctionRequest) Reset() {
	*x = InvokeConfigFunctionRequest{}
	mi := &file_oll_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeConfigFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeConfigFunctionRequest) ProtoMessage() {}

func (x *InvokeConfigFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oll_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeConfigFunctionRequest.ProtoReflect.Descriptor instead.
func (*InvokeConfigFunctionRequest) Descriptor() ([]byte, []int) {
	return file_oll_config_proto_rawDescGZIP(), []int{8}
}

func (x *InvokeConfigFunctionRequest) GetFunction() *ConfigFunctionRef {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *InvokeConfigFunctionRequest) GetArguments() []*ConfigValue {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type InvokeConfigFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ConfigValue         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeConfigFunctionResponse) Reset() {
	*x = InvokeConfigFunctionResponse{}
	mi := &file_oll_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeConfigFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeConfigFunctionResponse) ProtoMessage() {}

func (x *InvokeConfigFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oll_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeConfigFunctionResponse.ProtoReflect.Descriptor instead.
func (*InvokeConfigFunctionResponse) Descriptor() ([]byte, []int) {
	return file_oll_config_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeConfigFunctionResponse) GetResults() []*ConfigValue {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_oll_config_proto protoreflect.FileDescriptor

const file_oll_config_proto_rawDesc = "" +
	"\n" +
	"\x10oll/config.proto\x12\foll.protocol\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n" +
	"\x11ConfigFunctionRef\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vfunction_id\x18\x02 \x01(\tR\n" +
	"functionId\"?\n" +
	"\n" +
	"ConfigList\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.oll.protocol.ConfigValueR\x06values\"\xa2\x01\n" +
	"\tConfigMap\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.oll.protocol.ConfigMap.EntriesEntryR\aentries\x1aU\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.oll.protocol.ConfigValueR\x05value:\x028\x01\"\xcf\x04\n" +
	"\vConfigValue\x12;\n" +
	"\n" +
	"null_value\x18\x01 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\tnullValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12%\n" +
	"\rinteger_value\x18\x03 \x01(\x12H\x00R\fintegerValue\x12#\n" +
	"\fnumber_value\x18\x04 \x01(\x01H\x00R\vnumberValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\x06 \x01(\fH\x00R\n" +
	"bytesValue\x129\n" +
	"\n" +
	"list_value\x18\a \x01(\v2\x18.oll.protocol.ConfigListH\x00R\tlistValue\x126\n" +
	"\tmap_value\x18\b \x01(\v2\x17.oll.protocol.ConfigMapH\x00R\bmapValue\x12H\n" +
	"\x0efunction_value\x18\t \x01(\v2\x1f.oll.protocol.ConfigFunctionRefH\x00R\rfunctionValue\x12E\n" +
	"\x0ftimestamp_value\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12B\n" +
	"\x0eduration_value\x18\v \x01(\v2\x19.google.protobuf.DurationH\x00R\rdurationValueB\x06\n" +
	"\x04kind\"G\n" +
	"\x11ConfigPathSegment\x12\x12\n" +
	"\x03key\x18\x01 \x01(\tH\x00R\x03key\x12\x16\n" +
	"\x05index\x18\x02 \x01(\x04H\x00R\x05indexB\x06\n" +
	"\x04kind\"I\n" +
	"\n" +
	"ConfigPath\x12;\n" +
	"\bsegments\x18\x01 \x03(\v2\x1f.oll.protocol.ConfigPathSegmentR\bsegments\"@\n" +
	"\x10GetConfigRequest\x12,\n" +
	"\x04path\x18\x01 \x01(\v2\x18.oll.protocol.ConfigPathR\x04path\"D\n" +
	"\x11GetConfigResponse\x12/\n" +
	"\x05value\x18\x01 \x01(\v2\x19.oll.protocol.ConfigValueR\x05value\"\x93\x01\n" +
	"\x1bInvokeConfigFunctionRequest\x12;\n" +
	"\bfunction\x18\x01 \x01(\v2\x1f.oll.protocol.ConfigFunctionRefR\bfunction\x127\n" +
	"\targuments\x18\x02 \x03(\v2\x19.oll.protocol.ConfigValueR\targuments\"S\n" +
	"\x1cInvokeConfigFunctionResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.oll.protocol.ConfigValueR\aresultsb\x06proto3"

var (
	file_oll_config_proto_rawDescOnce sync.Once
	file_oll_config_proto_rawDescData []byte
)

func file_oll_config_proto_rawDescGZIP() []byte {
	file_oll_config_proto_rawDescOnce.Do(func() {
		file_oll_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oll_config_proto_rawDesc), len(file_oll_config_proto_rawDesc)))
	})
	return file_oll_config_proto_rawDescData
}

var file_oll_config_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_oll_config_proto_goTypes = []any{
	(*ConfigFunctionRef)(nil),            // 0: oll.protocol.ConfigFunctionRef
	(*ConfigList)(nil),                   // 1: oll.protocol.ConfigList
	(*ConfigMap)(nil),                    // 2: oll.protocol.ConfigMap
	(*ConfigValue)(nil),                  // 3: oll.protocol.ConfigValue
	(*ConfigPathSegment)(nil),            // 4: oll.protocol.ConfigPathSegment
	(*ConfigPath)(nil),                   // 5: oll.protocol.ConfigPath
	(*GetConfigRequest)(nil),             // 6: oll.protocol.GetConfigRequest
	(*GetConfigResponse)(nil),            // 7: oll.protocol.GetConfigResponse
	(*InvokeConfigFunctionRequest)(nil),  // 8: oll.protocol.InvokeConfigFunctionRequest
	(*InvokeConfigFunctionResponse)(nil), // 9: oll.protocol.InvokeConfigFunctionResponse
	nil,                                  // 10: oll.protocol.ConfigMap.EntriesEntry
	(structpb.NullValue)(0),              // 11: google.protobuf.NullValue
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),          // 13: google.protobuf.Duration
}
var file_oll_config_proto_depIdxs = []int32{
	3,  // 0: oll.protocol.ConfigList.values:type_name -> oll.protocol.ConfigValue
	10, // 1: oll.protocol.ConfigMap.entries:type_name -> oll.protocol.ConfigMap.EntriesEntry
	11, // 2: oll.protocol.ConfigValue.null_value:type_name -> google.protobuf.NullValue
	1,  // 3: oll.protocol.ConfigValue.list_value:type_name -> oll.protocol.ConfigList
	2,  // 4: oll.protocol.ConfigValue.map_value:type_name -> oll.protocol.ConfigMap
	0,  // 5: oll.protocol.ConfigValue.function_value:type_name -> oll.protocol.ConfigFunctionRef
	12, // 6: oll.protocol.ConfigValue.timestamp_value:type_name -> google.protobuf.Timestamp
	13, // 7: oll.protocol.ConfigValue.duration_value:type_name -> google.protobuf.Duration
	4,  // 8: oll.protocol.ConfigPath.segments:type_name -> oll.protocol.ConfigPathSegment
	5,  // 9: oll.protocol.GetConfigRequest.path:type_name -> oll.protocol.ConfigPath
	3,  // 10: oll.protocol.GetConfigResponse.value:type_name -> oll.protocol.ConfigValue
	0,  // 11: oll.protocol.InvokeConfigFunctionRequest.function:type_name -> oll.protocol.ConfigFunctionRef
	3,  // 12: oll.protocol.InvokeConfigFunctionRequest.arguments:type_name -> oll.protocol.ConfigValue
	3,  // 13: oll.protocol.InvokeConfigFunctionResponse.results:type_name -> oll.protocol.ConfigValue
	3,  // 14: oll.protocol.ConfigMap.EntriesEntry.value:type_name -> oll.protocol.ConfigValue
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_oll_config_proto_init() }
func file_oll_config_proto_init() {
	if File_oll_config_proto != nil {
		return
	}
	file_oll_config_proto_msgTypes[3].OneofWrappers = []any{
		(*ConfigValue_NullValue)(nil),
		(*ConfigValue_BoolValue)(nil),
		(*ConfigValue_IntegerValue)(nil),
		(*ConfigValue_NumberValue)(nil),
		(*ConfigValue_StringValue)(nil),
		(*ConfigValue_BytesValue)(nil),
		(*ConfigValue_ListValue)(nil),
		(*ConfigValue_MapValue)(nil),
		(*ConfigValue_FunctionValue)(nil),
		(*ConfigValue_TimestampValue)(nil),
		(*ConfigValue_DurationValue)(nil),
	}
	file_oll_config_proto_msgTypes[4].OneofWrappers = []any{
		(*ConfigPathSegment_Key)(nil),
		(*ConfigPathSegment_Index)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oll_config_proto_rawDesc), len(file_oll_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oll_config_proto_goTypes,
		DependencyIndexes: file_oll_config_proto_depIdxs,
		MessageInfos:      file_oll_config_proto_msgTypes,
	}.Build()
	File_oll_config_proto = out.File
	file_oll_config_proto_goTypes = nil
	file_oll_config_proto_depIdxs = nil
}
