// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: oll/plugin.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_RUNNING     JobState = 1
	JobState_JOB_STATE_SUCCEEDED   JobState = 2
	JobState_JOB_STATE_FAILED      JobState = 3
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_RUNNING",
		2: "JOB_STATE_SUCCEEDED",
		3: "JOB_STATE_FAILED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_RUNNING":     1,
		"JOB_STATE_SUCCEEDED":   2,
		"JOB_STATE_FAILED":      3,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_oll_plugin_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_oll_plugin_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{0}
}

type JobCancellationReason int32

const (
	JobCancellationReason_JOB_CANCELLATION_REASON_UNSPECIFIED  JobCancellationReason = 0
	JobCancellationReason_JOB_CANCELLATION_REASON_USER_REQUEST JobCancellationReason = 1
	JobCancellationReason_JOB_CANCELLATION_REASON_DEADLINE     JobCancellationReason = 2
)

// Enum value maps for JobCancellationReason.
var (
	JobCancellationReason_name = map[int32]string{
		0: "JOB_CANCELLATION_REASON_UNSPECIFIED",
		1: "JOB_CANCELLATION_REASON_USER_REQUEST",
		2: "JOB_CANCELLATION_REASON_DEADLINE",
	}
	JobCancellationReason_value = map[string]int32{
		"JOB_CANCELLATION_REASON_UNSPECIFIED":  0,
		"JOB_CANCELLATION_REASON_USER_REQUEST": 1,
		"JOB_CANCELLATION_REASON_DEADLINE":     2,
	}
)

func (x JobCancellationReason) Enum() *JobCancellationReason {
	p := new(JobCancellationReason)
	*p = x
	return p
}

func (x JobCancellationReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobCancellationReason) Descriptor() protoreflect.EnumDescriptor {
	return file_oll_plugin_proto_enumTypes[1].Descriptor()
}

func (JobCancellationReason) Type() protoreflect.EnumType {
	return &file_oll_plugin_proto_enumTypes[1]
}

func (x JobCancellationReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobCancellationReason.Descriptor instead.
func (JobCancellationReason) EnumDescriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{1}
}

type HostHello struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Node                      *NodeIdentity          `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	MaximumCallDepth          uint32                 `protobuf:"varint,2,opt,name=maximum_call_depth,json=maximumCallDepth,proto3" json:"maximum_call_depth,omitempty"`
	MaximumCausalDepth        uint32                 `protobuf:"varint,3,opt,name=maximum_causal_depth,json=maximumCausalDepth,proto3" json:"maximum_causal_depth,omitempty"`
	MaximumArtifactChunkBytes uint64                 `protobuf:"varint,4,opt,name=maximum_artifact_chunk_bytes,json=maximumArtifactChunkBytes,proto3" json:"maximum_artifact_chunk_bytes,omitempty"`
	PluginId                  *PluginId              `protobuf:"bytes,5,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginName                *PluginName            `protobuf:"bytes,6,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *HostHello) Reset() {
	*x = HostHello{}
	mi := &file_oll_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostHello) ProtoMessage() {}

func (x *HostHello) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostHello.ProtoReflect.Descriptor instead.
func (*HostHello) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HostHello) GetNode() *NodeIdentity {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *HostHello) GetMaximumCallDepth() uint32 {
	if x != nil {
		return x.MaximumCallDepth
	}
	return 0
}

func (x *HostHello) GetMaximumCausalDepth() uint32 {
	if x != nil {
		return x.MaximumCausalDepth
	}
	return 0
}

func (x *HostHello) GetMaximumArtifactChunkBytes() uint64 {
	if x != nil {
		return x.MaximumArtifactChunkBytes
	}
	return 0
}

func (x *HostHello) GetPluginId() *PluginId {
	if x != nil {
		return x.PluginId
	}
	return nil
}

func (x *HostHello) GetPluginName() *PluginName {
	if x != nil {
		return x.PluginName
	}
	return nil
}

type ActionDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionDescriptor) Reset() {
	*x = ActionDescriptor{}
	mi := &file_oll_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDescriptor) ProtoMessage() {}

func (x *ActionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDescriptor.ProtoReflect.Descriptor instead.
func (*ActionDescriptor) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ActionDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PluginHello struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PluginId   *PluginId              `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginName *PluginName            `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Actions    []*ActionDescriptor    `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	// Informational build string only; package/release selection never parses it.
	PluginVersion string `protobuf:"bytes,4,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginHello) Reset() {
	*x = PluginHello{}
	mi := &file_oll_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginHello) ProtoMessage() {}

func (x *PluginHello) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginHello.ProtoReflect.Descriptor instead.
func (*PluginHello) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginHello) GetPluginId() *PluginId {
	if x != nil {
		return x.PluginId
	}
	return nil
}

func (x *PluginHello) GetPluginName() *PluginName {
	if x != nil {
		return x.PluginName
	}
	return nil
}

func (x *PluginHello) GetActions() []*ActionDescriptor {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PluginHello) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

type SessionReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReady) Reset() {
	*x = SessionReady{}
	mi := &file_oll_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReady) ProtoMessage() {}

func (x *SessionReady) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReady.ProtoReflect.Descriptor instead.
func (*SessionReady) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{3}
}

type ActionInvocation struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Action string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// Generic action calls use shell-style UTF-8 argv semantics. oll preserves
	// order, duplicates, empty strings, and values beginning with '-'.
	Arguments     []string `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionInvocation) Reset() {
	*x = ActionInvocation{}
	mi := &file_oll_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionInvocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionInvocation) ProtoMessage() {}

func (x *ActionInvocation) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionInvocation.ProtoReflect.Descriptor instead.
func (*ActionInvocation) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ActionInvocation) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionInvocation) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type StartJobRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    *PluginJobId           `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Deadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	// Types that are valid to be assigned to Invocation:
	//
	//	*StartJobRequest_Action
	Invocation    isStartJobRequest_Invocation `protobuf_oneof:"invocation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_oll_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *StartJobRequest) GetJobId() *PluginJobId {
	if x != nil {
		return x.JobId
	}
	return nil
}

func (x *StartJobRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *StartJobRequest) GetInvocation() isStartJobRequest_Invocation {
	if x != nil {
		return x.Invocation
	}
	return nil
}

func (x *StartJobRequest) GetAction() *ActionInvocation {
	if x != nil {
		if x, ok := x.Invocation.(*StartJobRequest_Action); ok {
			return x.Action
		}
	}
	return nil
}

type isStartJobRequest_Invocation interface {
	isStartJobRequest_Invocation()
}

type StartJobRequest_Action struct {
	Action *ActionInvocation `protobuf:"bytes,3,opt,name=action,proto3,oneof"`
}

func (*StartJobRequest_Action) isStartJobRequest_Invocation() {}

type JobAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *PluginJobId           `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAccepted) Reset() {
	*x = JobAccepted{}
	mi := &file_oll_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAccepted) ProtoMessage() {}

func (x *JobAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAccepted.ProtoReflect.Descriptor instead.
func (*JobAccepted) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *JobAccepted) GetJobId() *PluginJobId {
	if x != nil {
		return x.JobId
	}
	return nil
}

type JobUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *PluginJobId           `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=oll.protocol.JobState" json:"state,omitempty"`
	Progress      *float64               `protobuf:"fixed64,3,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	StatusMessage *string                `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3,oneof" json:"status_message,omitempty"`
	Result        *ConfigValue           `protobuf:"bytes,5,opt,name=result,proto3,oneof" json:"result,omitempty"`
	Error         *ProtocolError         `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// Terminal updates list only artifacts that oll has acknowledged as stored.
	Artifacts     []*ArtifactDescriptor `protobuf:"bytes,7,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobUpdate) Reset() {
	*x = JobUpdate{}
	mi := &file_oll_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobUpdate) ProtoMessage() {}

func (x *JobUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobUpdate.ProtoReflect.Descriptor instead.
func (*JobUpdate) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *JobUpdate) GetJobId() *PluginJobId {
	if x != nil {
		return x.JobId
	}
	return nil
}

func (x *JobUpdate) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobUpdate) GetProgress() float64 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *JobUpdate) GetStatusMessage() string {
	if x != nil && x.StatusMessage != nil {
		return *x.StatusMessage
	}
	return ""
}

func (x *JobUpdate) GetResult() *ConfigValue {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *JobUpdate) GetError() *ProtocolError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *JobUpdate) GetArtifacts() []*ArtifactDescriptor {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    *PluginArtifactId      `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactDescriptor) Reset() {
	*x = ArtifactDescriptor{}
	mi := &file_oll_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactDescriptor) ProtoMessage() {}

func (x *ArtifactDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactDescriptor.ProtoReflect.Descriptor instead.
func (*ArtifactDescriptor) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ArtifactDescriptor) GetArtifactId() *PluginArtifactId {
	if x != nil {
		return x.ArtifactId
	}
	return nil
}

func (x *ArtifactDescriptor) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ArtifactDescriptor) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ArtifactDescriptor) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactDescriptor) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type ArtifactTransferStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *PluginJobId           `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Artifact      *ArtifactDescriptor    `protobuf:"bytes,2,opt,name=artifact,proto3" json:"artifact,omitempty"`
	ChunkCount    uint32                 `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactTransferStart) Reset() {
	*x = ArtifactTransferStart{}
	mi := &file_oll_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactTransferStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactTransferStart) ProtoMessage() {}

func (x *ArtifactTransferStart) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactTransferStart.ProtoReflect.Descriptor instead.
func (*ArtifactTransferStart) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ArtifactTransferStart) GetJobId() *PluginJobId {
	if x != nil {
		return x.JobId
	}
	return nil
}

func (x *ArtifactTransferStart) GetArtifact() *ArtifactDescriptor {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *ArtifactTransferStart) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type ArtifactTransferAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    *PluginArtifactId      `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactTransferAccepted) Reset() {
	*x = ArtifactTransferAccepted{}
	mi := &file_oll_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactTransferAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactTransferAccepted) ProtoMessage() {}

func (x *ArtifactTransferAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactTransferAccepted.ProtoReflect.Descriptor instead.
func (*ArtifactTransferAccepted) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ArtifactTransferAccepted) GetArtifactId() *PluginArtifactId {
	if x != nil {
		return x.ArtifactId
	}
	return nil
}

type ArtifactTransferChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    *PluginArtifactId      `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactTransferChunk) Reset() {
	*x = ArtifactTransferChunk{}
	mi := &file_oll_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactTransferChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactTransferChunk) ProtoMessage() {}

func (x *ArtifactTransferChunk) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactTransferChunk.ProtoReflect.Descriptor instead.
func (*ArtifactTransferChunk) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ArtifactTransferChunk) GetArtifactId() *PluginArtifactId {
	if x != nil {
		return x.ArtifactId
	}
	return nil
}

func (x *ArtifactTransferChunk) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ArtifactTransferChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArtifactTransferComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    *PluginArtifactId      `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactTransferComplete) Reset() {
	*x = ArtifactTransferComplete{}
	mi := &file_oll_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactTransferComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactTransferComplete) ProtoMessage() {}

func (x *ArtifactTransferComplete) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactTransferComplete.ProtoReflect.Descriptor instead.
func (*ArtifactTransferComplete) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ArtifactTransferComplete) GetArtifactId() *PluginArtifactId {
	if x != nil {
		return x.ArtifactId
	}
	return nil
}

type ArtifactStored struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    *PluginArtifactId      `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactStored) Reset() {
	*x = ArtifactStored{}
	mi := &file_oll_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactStored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactStored) ProtoMessage() {}

func (x *ArtifactStored) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactStored.ProtoReflect.Descriptor instead.
func (*ArtifactStored) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ArtifactStored) GetArtifactId() *PluginArtifactId {
	if x != nil {
		return x.ArtifactId
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *PluginJobId           `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        JobCancellationReason  `protobuf:"varint,2,opt,name=reason,proto3,enum=oll.protocol.JobCancellationReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_oll_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *CancelJobRequest) GetJobId() *PluginJobId {
	if x != nil {
		return x.JobId
	}
	return nil
}

func (x *CancelJobRequest) GetReason() JobCancellationReason {
	if x != nil {
		return x.Reason
	}
	return JobCancellationReason_JOB_CANCELLATION_REASON_UNSPECIFIED
}

type CancelJobAcknowledged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *PluginJobId           `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobAcknowledged) Reset() {
	*x = CancelJobAcknowledged{}
	mi := &file_oll_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobAcknowledged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobAcknowledged) ProtoMessage() {}

func (x *CancelJobAcknowledged) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobAcknowledged.ProtoReflect.Descriptor instead.
func (*CancelJobAcknowledged) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *CancelJobAcknowledged) GetJobId() *PluginJobId {
	if x != nil {
		return x.JobId
	}
	return nil
}

type HostCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Call:
	//
	//	*HostCallRequest_ReadDocument
	//	*HostCallRequest_ListDirectory
	//	*HostCallRequest_GetDirectoryTree
	//	*HostCallRequest_ReadCrdt
	//	*HostCallRequest_CommitDocuments
	//	*HostCallRequest_GetConfig
	//	*HostCallRequest_InvokeConfigFunction
	Call          isHostCallRequest_Call `protobuf_oneof:"call"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCallRequest) Reset() {
	*x = HostCallRequest{}
	mi := &file_oll_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCallRequest) ProtoMessage() {}

func (x *HostCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCallRequest.ProtoReflect.Descriptor instead.
func (*HostCallRequest) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *HostCallRequest) GetCall() isHostCallRequest_Call {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *HostCallRequest) GetReadDocument() *ReadDocumentRequest {
	if x != nil {
		if x, ok := x.Call.(*HostCallRequest_ReadDocument); ok {
			return x.ReadDocument
		}
	}
	return nil
}

func (x *HostCallRequest) GetListDirectory() *ListDirectoryRequest {
	if x != nil {
		if x, ok := x.Call.(*HostCallRequest_ListDirectory); ok {
			return x.ListDirectory
		}
	}
	return nil
}

func (x *HostCallRequest) GetGetDirectoryTree() *GetDirectoryTreeRequest {
	if x != nil {
		if x, ok := x.Call.(*HostCallRequest_GetDirectoryTree); ok {
			return x.GetDirectoryTree
		}
	}
	return nil
}

func (x *HostCallRequest) GetReadCrdt() *ReadCrdtRequest {
	if x != nil {
		if x, ok := x.Call.(*HostCallRequest_ReadCrdt); ok {
			return x.ReadCrdt
		}
	}
	return nil
}

func (x *HostCallRequest) GetCommitDocuments() *CommitDocumentsRequest {
	if x != nil {
		if x, ok := x.Call.(*HostCallRequest_CommitDocuments); ok {
			return x.CommitDocuments
		}
	}
	return nil
}

func (x *HostCallRequest) GetGetConfig() *GetConfigRequest {
	if x != nil {
		if x, ok := x.Call.(*HostCallRequest_GetConfig); ok {
			return x.GetConfig
		}
	}
	return nil
}

func (x *HostCallRequest) GetInvokeConfigFunction() *InvokeConfigFunctionRequest {
	if x != nil {
		if x, ok := x.Call.(*HostCallRequest_InvokeConfigFunction); ok {
			return x.InvokeConfigFunction
		}
	}
	return nil
}

type isHostCallRequest_Call interface {
	isHostCallRequest_Call()
}

type HostCallRequest_ReadDocument struct {
	ReadDocument *ReadDocumentRequest `protobuf:"bytes,1,opt,name=read_document,json=readDocument,proto3,oneof"`
}

type HostCallRequest_ListDirectory struct {
	ListDirectory *ListDirectoryRequest `protobuf:"bytes,2,opt,name=list_directory,json=listDirectory,proto3,oneof"`
}

type HostCallRequest_GetDirectoryTree struct {
	GetDirectoryTree *GetDirectoryTreeRequest `protobuf:"bytes,3,opt,name=get_directory_tree,json=getDirectoryTree,proto3,oneof"`
}

type HostCallRequest_ReadCrdt struct {
	ReadCrdt *ReadCrdtRequest `protobuf:"bytes,4,opt,name=read_crdt,json=readCrdt,proto3,oneof"`
}

type HostCallRequest_CommitDocuments struct {
	CommitDocuments *CommitDocumentsRequest `protobuf:"bytes,5,opt,name=commit_documents,json=commitDocuments,proto3,oneof"`
}

type HostCallRequest_GetConfig struct {
	GetConfig *GetConfigRequest `protobuf:"bytes,6,opt,name=get_config,json=getConfig,proto3,oneof"`
}

type HostCallRequest_InvokeConfigFunction struct {
	InvokeConfigFunction *InvokeConfigFunctionRequest `protobuf:"bytes,7,opt,name=invoke_config_function,json=invokeConfigFunction,proto3,oneof"`
}

func (*HostCallRequest_ReadDocument) isHostCallRequest_Call() {}

func (*HostCallRequest_ListDirectory) isHostCallRequest_Call() {}

func (*HostCallRequest_GetDirectoryTree) isHostCallRequest_Call() {}

func (*HostCallRequest_ReadCrdt) isHostCallRequest_Call() {}

func (*HostCallRequest_CommitDocuments) isHostCallRequest_Call() {}

func (*HostCallRequest_GetConfig) isHostCallRequest_Call() {}

func (*HostCallRequest_InvokeConfigFunction) isHostCallRequest_Call() {}

type HostCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*HostCallResponse_ReadDocument
	//	*HostCallResponse_ListDirectory
	//	*HostCallResponse_GetDirectoryTree
	//	*HostCallResponse_ReadCrdt
	//	*HostCallResponse_CommitDocuments
	//	*HostCallResponse_GetConfig
	//	*HostCallResponse_InvokeConfigFunction
	//	*HostCallResponse_Error
	Result        isHostCallResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCallResponse) Reset() {
	*x = HostCallResponse{}
	mi := &file_oll_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCallResponse) ProtoMessage() {}

func (x *HostCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCallResponse.ProtoReflect.Descriptor instead.
func (*HostCallResponse) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *HostCallResponse) GetResult() isHostCallResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HostCallResponse) GetReadDocument() *ReadDocumentResponse {
	if x != nil {
		if x, ok := x.Result.(*HostCallResponse_ReadDocument); ok {
			return x.ReadDocument
		}
	}
	return nil
}

func (x *HostCallResponse) GetListDirectory() *ListDirectoryResponse {
	if x != nil {
		if x, ok := x.Result.(*HostCallResponse_ListDirectory); ok {
			return x.ListDirectory
		}
	}
	return nil
}

func (x *HostCallResponse) GetGetDirectoryTree() *GetDirectoryTreeResponse {
	if x != nil {
		if x, ok := x.Result.(*HostCallResponse_GetDirectoryTree); ok {
			return x.GetDirectoryTree
		}
	}
	return nil
}

func (x *HostCallResponse) GetReadCrdt() *ReadCrdtResponse {
	if x != nil {
		if x, ok := x.Result.(*HostCallResponse_ReadCrdt); ok {
			return x.ReadCrdt
		}
	}
	return nil
}

func (x *HostCallResponse) GetCommitDocuments() *CommitDocumentsResponse {
	if x != nil {
		if x, ok := x.Result.(*HostCallResponse_CommitDocuments); ok {
			return x.CommitDocuments
		}
	}
	return nil
}

func (x *HostCallResponse) GetGetConfig() *GetConfigResponse {
	if x != nil {
		if x, ok := x.Result.(*HostCallResponse_GetConfig); ok {
			return x.GetConfig
		}
	}
	return nil
}

func (x *HostCallResponse) GetInvokeConfigFunction() *InvokeConfigFunctionResponse {
	if x != nil {
		if x, ok := x.Result.(*HostCallResponse_InvokeConfigFunction); ok {
			return x.InvokeConfigFunction
		}
	}
	return nil
}

func (x *HostCallResponse) GetError() *ProtocolError {
	if x != nil {
		if x, ok := x.Result.(*HostCallResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isHostCallResponse_Result interface {
	isHostCallResponse_Result()
}

type HostCallResponse_ReadDocument struct {
	ReadDocument *ReadDocumentResponse `protobuf:"bytes,1,opt,name=read_document,json=readDocument,proto3,oneof"`
}

type HostCallResponse_ListDirectory struct {
	ListDirectory *ListDirectoryResponse `protobuf:"bytes,2,opt,name=list_directory,json=listDirectory,proto3,oneof"`
}

type HostCallResponse_GetDirectoryTree struct {
	GetDirectoryTree *GetDirectoryTreeResponse `protobuf:"bytes,3,opt,name=get_directory_tree,json=getDirectoryTree,proto3,oneof"`
}

type HostCallResponse_ReadCrdt struct {
	ReadCrdt *ReadCrdtResponse `protobuf:"bytes,4,opt,name=read_crdt,json=readCrdt,proto3,oneof"`
}

type HostCallResponse_CommitDocuments struct {
	CommitDocuments *CommitDocumentsResponse `protobuf:"bytes,5,opt,name=commit_documents,json=commitDocuments,proto3,oneof"`
}

type HostCallResponse_GetConfig struct {
	GetConfig *GetConfigResponse `protobuf:"bytes,6,opt,name=get_config,json=getConfig,proto3,oneof"`
}

type HostCallResponse_InvokeConfigFunction struct {
	InvokeConfigFunction *InvokeConfigFunctionResponse `protobuf:"bytes,7,opt,name=invoke_config_function,json=invokeConfigFunction,proto3,oneof"`
}

type HostCallResponse_Error struct {
	Error *ProtocolError `protobuf:"bytes,15,opt,name=error,proto3,oneof"`
}

func (*HostCallResponse_ReadDocument) isHostCallResponse_Result() {}

func (*HostCallResponse_ListDirectory) isHostCallResponse_Result() {}

func (*HostCallResponse_GetDirectoryTree) isHostCallResponse_Result() {}

func (*HostCallResponse_ReadCrdt) isHostCallResponse_Result() {}

func (*HostCallResponse_CommitDocuments) isHostCallResponse_Result() {}

func (*HostCallResponse_GetConfig) isHostCallResponse_Result() {}

func (*HostCallResponse_InvokeConfigFunction) isHostCallResponse_Result() {}

func (*HostCallResponse_Error) isHostCallResponse_Result() {}

type LogRecord struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         LogLevel                `protobuf:"varint,2,opt,name=level,proto3,enum=oll.protocol.LogLevel" json:"level,omitempty"`
	Target        string                  `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Message       string                  `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]*ConfigValue `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_oll_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *LogRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogRecord) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogRecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetFields() map[string]*ConfigValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_oll_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *Heartbeat) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type ShutdownRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Reason string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// The plugin should acknowledge and exit before this deadline. Host signal
	// escalation after the deadline is enforcement of this same graceful request,
	// not another public operation.
	GracePeriodDeadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=grace_period_deadline,json=gracePeriodDeadline,proto3" json:"grace_period_deadline,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_oll_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *ShutdownRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ShutdownRequest) GetGracePeriodDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.GracePeriodDeadline
	}
	return nil
}

type ShutdownAcknowledged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownAcknowledged) Reset() {
	*x = ShutdownAcknowledged{}
	mi := &file_oll_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownAcknowledged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownAcknowledged) ProtoMessage() {}

func (x *ShutdownAcknowledged) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownAcknowledged.ProtoReflect.Descriptor instead.
func (*ShutdownAcknowledged) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{21}
}

// Each sender owns an independent sequence. IDs are nonzero and strictly
// increase relative to that sender's preceding envelope; gaps are valid.
// Direct responses set reply_to. New nested calls set parent_call_id and
// increment call_depth.
type PluginEnvelope struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        uint64                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReplyTo          *uint64                `protobuf:"varint,2,opt,name=reply_to,json=replyTo,proto3,oneof" json:"reply_to,omitempty"`
	SessionId        string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PluginInstanceId string                 `protobuf:"bytes,4,opt,name=plugin_instance_id,json=pluginInstanceId,proto3" json:"plugin_instance_id,omitempty"`
	Trace            *TraceContext          `protobuf:"bytes,5,opt,name=trace,proto3" json:"trace,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PluginEnvelope_HostHello
	//	*PluginEnvelope_PluginHello
	//	*PluginEnvelope_Ready
	//	*PluginEnvelope_StartJob
	//	*PluginEnvelope_JobAccepted
	//	*PluginEnvelope_JobUpdate
	//	*PluginEnvelope_HostCall
	//	*PluginEnvelope_HostResult
	//	*PluginEnvelope_Log
	//	*PluginEnvelope_Heartbeat
	//	*PluginEnvelope_Shutdown
	//	*PluginEnvelope_ShutdownAcknowledged
	//	*PluginEnvelope_ProtocolError
	//	*PluginEnvelope_ArtifactStart
	//	*PluginEnvelope_ArtifactAccepted
	//	*PluginEnvelope_ArtifactChunk
	//	*PluginEnvelope_ArtifactComplete
	//	*PluginEnvelope_ArtifactStored
	//	*PluginEnvelope_CancelJob
	//	*PluginEnvelope_CancelJobAcknowledged
	Payload       isPluginEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginEnvelope) Reset() {
	*x = PluginEnvelope{}
	mi := &file_oll_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEnvelope) ProtoMessage() {}

func (x *PluginEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_oll_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEnvelope.ProtoReflect.Descriptor instead.
func (*PluginEnvelope) Descriptor() ([]byte, []int) {
	return file_oll_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *PluginEnvelope) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *PluginEnvelope) GetReplyTo() uint64 {
	if x != nil && x.ReplyTo != nil {
		return *x.ReplyTo
	}
	return 0
}

func (x *PluginEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PluginEnvelope) GetPluginInstanceId() string {
	if x != nil {
		return x.PluginInstanceId
	}
	return ""
}

func (x *PluginEnvelope) GetTrace() *TraceContext {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *PluginEnvelope) GetPayload() isPluginEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PluginEnvelope) GetHostHello() *HostHello {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_HostHello); ok {
			return x.HostHello
		}
	}
	return nil
}

func (x *PluginEnvelope) GetPluginHello() *PluginHello {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_PluginHello); ok {
			return x.PluginHello
		}
	}
	return nil
}

func (x *PluginEnvelope) GetReady() *SessionReady {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *PluginEnvelope) GetStartJob() *StartJobRequest {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_StartJob); ok {
			return x.StartJob
		}
	}
	return nil
}

func (x *PluginEnvelope) GetJobAccepted() *JobAccepted {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_JobAccepted); ok {
			return x.JobAccepted
		}
	}
	return nil
}

func (x *PluginEnvelope) GetJobUpdate() *JobUpdate {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_JobUpdate); ok {
			return x.JobUpdate
		}
	}
	return nil
}

func (x *PluginEnvelope) GetHostCall() *HostCallRequest {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_HostCall); ok {
			return x.HostCall
		}
	}
	return nil
}

func (x *PluginEnvelope) GetHostResult() *HostCallResponse {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_HostResult); ok {
			return x.HostResult
		}
	}
	return nil
}

func (x *PluginEnvelope) GetLog() *LogRecord {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *PluginEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *PluginEnvelope) GetShutdown() *ShutdownRequest {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *PluginEnvelope) GetShutdownAcknowledged() *ShutdownAcknowledged {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_ShutdownAcknowledged); ok {
			return x.ShutdownAcknowledged
		}
	}
	return nil
}

func (x *PluginEnvelope) GetProtocolError() *ProtocolError {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_ProtocolError); ok {
			return x.ProtocolError
		}
	}
	return nil
}

func (x *PluginEnvelope) GetArtifactStart() *ArtifactTransferStart {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_ArtifactStart); ok {
			return x.ArtifactStart
		}
	}
	return nil
}

func (x *PluginEnvelope) GetArtifactAccepted() *ArtifactTransferAccepted {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_ArtifactAccepted); ok {
			return x.ArtifactAccepted
		}
	}
	return nil
}

func (x *PluginEnvelope) GetArtifactChunk() *ArtifactTransferChunk {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_ArtifactChunk); ok {
			return x.ArtifactChunk
		}
	}
	return nil
}

func (x *PluginEnvelope) GetArtifactComplete() *ArtifactTransferComplete {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_ArtifactComplete); ok {
			return x.ArtifactComplete
		}
	}
	return nil
}

func (x *PluginEnvelope) GetArtifactStored() *ArtifactStored {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_ArtifactStored); ok {
			return x.ArtifactStored
		}
	}
	return nil
}

func (x *PluginEnvelope) GetCancelJob() *CancelJobRequest {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_CancelJob); ok {
			return x.CancelJob
		}
	}
	return nil
}

func (x *PluginEnvelope) GetCancelJobAcknowledged() *CancelJobAcknowledged {
	if x != nil {
		if x, ok := x.Payload.(*PluginEnvelope_CancelJobAcknowledged); ok {
			return x.CancelJobAcknowledged
		}
	}
	return nil
}

type isPluginEnvelope_Payload interface {
	isPluginEnvelope_Payload()
}

type PluginEnvelope_HostHello struct {
	HostHello *HostHello `protobuf:"bytes,10,opt,name=host_hello,json=hostHello,proto3,oneof"`
}

type PluginEnvelope_PluginHello struct {
	PluginHello *PluginHello `protobuf:"bytes,11,opt,name=plugin_hello,json=pluginHello,proto3,oneof"`
}

type PluginEnvelope_Ready struct {
	Ready *SessionReady `protobuf:"bytes,12,opt,name=ready,proto3,oneof"`
}

type PluginEnvelope_StartJob struct {
	StartJob *StartJobRequest `protobuf:"bytes,13,opt,name=start_job,json=startJob,proto3,oneof"`
}

type PluginEnvelope_JobAccepted struct {
	JobAccepted *JobAccepted `protobuf:"bytes,14,opt,name=job_accepted,json=jobAccepted,proto3,oneof"`
}

type PluginEnvelope_JobUpdate struct {
	JobUpdate *JobUpdate `protobuf:"bytes,15,opt,name=job_update,json=jobUpdate,proto3,oneof"`
}

type PluginEnvelope_HostCall struct {
	HostCall *HostCallRequest `protobuf:"bytes,16,opt,name=host_call,json=hostCall,proto3,oneof"`
}

type PluginEnvelope_HostResult struct {
	HostResult *HostCallResponse `protobuf:"bytes,17,opt,name=host_result,json=hostResult,proto3,oneof"`
}

type PluginEnvelope_Log struct {
	Log *LogRecord `protobuf:"bytes,18,opt,name=log,proto3,oneof"`
}

type PluginEnvelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,19,opt,name=heartbeat,proto3,oneof"`
}

type PluginEnvelope_Shutdown struct {
	Shutdown *ShutdownRequest `protobuf:"bytes,20,opt,name=shutdown,proto3,oneof"`
}

type PluginEnvelope_ShutdownAcknowledged struct {
	ShutdownAcknowledged *ShutdownAcknowledged `protobuf:"bytes,21,opt,name=shutdown_acknowledged,json=shutdownAcknowledged,proto3,oneof"`
}

type PluginEnvelope_ProtocolError struct {
	ProtocolError *ProtocolError `protobuf:"bytes,22,opt,name=protocol_error,json=protocolError,proto3,oneof"`
}

type PluginEnvelope_ArtifactStart struct {
	ArtifactStart *ArtifactTransferStart `protobuf:"bytes,23,opt,name=artifact_start,json=artifactStart,proto3,oneof"`
}

type PluginEnvelope_ArtifactAccepted struct {
	ArtifactAccepted *ArtifactTransferAccepted `protobuf:"bytes,24,opt,name=artifact_accepted,json=artifactAccepted,proto3,oneof"`
}

type PluginEnvelope_ArtifactChunk struct {
	ArtifactChunk *ArtifactTransferChunk `protobuf:"bytes,25,opt,name=artifact_chunk,json=artifactChunk,proto3,oneof"`
}

type PluginEnvelope_ArtifactComplete struct {
	ArtifactComplete *ArtifactTransferComplete `protobuf:"bytes,26,opt,name=artifact_complete,json=artifactComplete,proto3,oneof"`
}

type PluginEnvelope_ArtifactStored struct {
	ArtifactStored *ArtifactStored `protobuf:"bytes,27,opt,name=artifact_stored,json=artifactStored,proto3,oneof"`
}

type PluginEnvelope_CancelJob struct {
	CancelJob *CancelJobRequest `protobuf:"bytes,28,opt,name=cancel_job,json=cancelJob,proto3,oneof"`
}

type PluginEnvelope_CancelJobAcknowledged struct {
	CancelJobAcknowledged *CancelJobAcknowledged `protobuf:"bytes,29,opt,name=cancel_job_acknowledged,json=cancelJobAcknowledged,proto3,oneof"`
}

func (*PluginEnvelope_HostHello) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_PluginHello) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_Ready) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_StartJob) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_JobAccepted) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_JobUpdate) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_HostCall) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_HostResult) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_Log) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_Heartbeat) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_Shutdown) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_ShutdownAcknowledged) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_ProtocolError) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_ArtifactStart) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_ArtifactAccepted) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_ArtifactChunk) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_ArtifactComplete) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_ArtifactStored) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_CancelJob) isPluginEnvelope_Payload() {}

func (*PluginEnvelope_CancelJobAcknowledged) isPluginEnvelope_Payload() {}

var File_oll_plugin_proto protoreflect.FileDescriptor

const file_oll_plugin_proto_rawDesc = "" +
	"\n" +
	"\x10oll/plugin.proto\x12\foll.protocol\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10oll/common.proto\x1a\x10oll/config.proto\x1a\x12oll/document.proto\"\xcc\x02\n" +
	"\tHostHello\x12.\n" +
	"\x04node\x18\x01 \x01(\v2\x1a.oll.protocol.NodeIdentityR\x04node\x12,\n" +
	"\x12maximum_call_depth\x18\x02 \x01(\rR\x10maximumCallDepth\x120\n" +
	"\x14maximum_causal_depth\x18\x03 \x01(\rR\x12maximumCausalDepth\x12?\n" +
	"\x1cmaximum_artifact_chunk_bytes\x18\x04 \x01(\x04R\x19maximumArtifactChunkBytes\x123\n" +
	"\tplugin_id\x18\x05 \x01(\v2\x16.oll.protocol.PluginIdR\bpluginId\x129\n" +
	"\vplugin_name\x18\x06 \x01(\v2\x18.oll.protocol.PluginNameR\n" +
	"pluginName\"H\n" +
	"\x10ActionDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xde\x01\n" +
	"\vPluginHello\x123\n" +
	"\tplugin_id\x18\x01 \x01(\v2\x16.oll.protocol.PluginIdR\bpluginId\x129\n" +
	"\vplugin_name\x18\x02 \x01(\v2\x18.oll.protocol.PluginNameR\n" +
	"pluginName\x128\n" +
	"\aactions\x18\x03 \x03(\v2\x1e.oll.protocol.ActionDescriptorR\aactions\x12%\n" +
	"\x0eplugin_version\x18\x04 \x01(\tR\rpluginVersion\"\x0e\n" +
	"\fSessionReady\"H\n" +
	"\x10ActionInvocation\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1c\n" +
	"\targuments\x18\x02 \x03(\tR\targuments\"\xd5\x01\n" +
	"\x0fStartJobRequest\x120\n" +
	"\x06job_id\x18\x01 \x01(\v2\x19.oll.protocol.PluginJobIdR\x05jobId\x12;\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bdeadline\x88\x01\x01\x128\n" +
	"\x06action\x18\x03 \x01(\v2\x1e.oll.protocol.ActionInvocationH\x00R\x06actionB\f\n" +
	"\n" +
	"invocationB\v\n" +
	"\t_deadline\"?\n" +
	"\vJobAccepted\x120\n" +
	"\x06job_id\x18\x01 \x01(\v2\x19.oll.protocol.PluginJobIdR\x05jobId\"\x9d\x03\n" +
	"\tJobUpdate\x120\n" +
	"\x06job_id\x18\x01 \x01(\v2\x19.oll.protocol.PluginJobIdR\x05jobId\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.oll.protocol.JobStateR\x05state\x12\x1f\n" +
	"\bprogress\x18\x03 \x01(\x01H\x00R\bprogress\x88\x01\x01\x12*\n" +
	"\x0estatus_message\x18\x04 \x01(\tH\x01R\rstatusMessage\x88\x01\x01\x126\n" +
	"\x06result\x18\x05 \x01(\v2\x19.oll.protocol.ConfigValueH\x02R\x06result\x88\x01\x01\x126\n" +
	"\x05error\x18\x06 \x01(\v2\x1b.oll.protocol.ProtocolErrorH\x03R\x05error\x88\x01\x01\x12>\n" +
	"\tartifacts\x18\a \x03(\v2 .oll.protocol.ArtifactDescriptorR\tartifactsB\v\n" +
	"\t_progressB\x11\n" +
	"\x0f_status_messageB\t\n" +
	"\a_resultB\b\n" +
	"\x06_error\"\xc8\x01\n" +
	"\x12ArtifactDescriptor\x12?\n" +
	"\vartifact_id\x18\x01 \x01(\v2\x1e.oll.protocol.PluginArtifactIdR\n" +
	"artifactId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\fR\x06sha256\"\xa8\x01\n" +
	"\x15ArtifactTransferStart\x120\n" +
	"\x06job_id\x18\x01 \x01(\v2\x19.oll.protocol.PluginJobIdR\x05jobId\x12<\n" +
	"\bartifact\x18\x02 \x01(\v2 .oll.protocol.ArtifactDescriptorR\bartifact\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\rR\n" +
	"chunkCount\"[\n" +
	"\x18ArtifactTransferAccepted\x12?\n" +
	"\vartifact_id\x18\x01 \x01(\v2\x1e.oll.protocol.PluginArtifactIdR\n" +
	"artifactId\"\x8d\x01\n" +
	"\x15ArtifactTransferChunk\x12?\n" +
	"\vartifact_id\x18\x01 \x01(\v2\x1e.oll.protocol.PluginArtifactIdR\n" +
	"artifactId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\rR\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"[\n" +
	"\x18ArtifactTransferComplete\x12?\n" +
	"\vartifact_id\x18\x01 \x01(\v2\x1e.oll.protocol.PluginArtifactIdR\n" +
	"artifactId\"Q\n" +
	"\x0eArtifactStored\x12?\n" +
	"\vartifact_id\x18\x01 \x01(\v2\x1e.oll.protocol.PluginArtifactIdR\n" +
	"artifactId\"\x81\x01\n" +
	"\x10CancelJobRequest\x120\n" +
	"\x06job_id\x18\x01 \x01(\v2\x19.oll.protocol.PluginJobIdR\x05jobId\x12;\n" +
	"\x06reason\x18\x02 \x01(\x0e2#.oll.protocol.JobCancellationReasonR\x06reason\"I\n" +
	"\x15CancelJobAcknowledged\x120\n" +
	"\x06job_id\x18\x01 \x01(\v2\x19.oll.protocol.PluginJobIdR\x05jobId\"\xbc\x04\n" +
	"\x0fHostCallRequest\x12H\n" +
	"\rread_document\x18\x01 \x01(\v2!.oll.protocol.ReadDocumentRequestH\x00R\freadDocument\x12K\n" +
	"\x0elist_directory\x18\x02 \x01(\v2\".oll.protocol.ListDirectoryRequestH\x00R\rlistDirectory\x12U\n" +
	"\x12get_directory_tree\x18\x03 \x01(\v2%.oll.protocol.GetDirectoryTreeRequestH\x00R\x10getDirectoryTree\x12<\n" +
	"\tread_crdt\x18\x04 \x01(\v2\x1d.oll.protocol.ReadCrdtRequestH\x00R\breadCrdt\x12Q\n" +
	"\x10commit_documents\x18\x05 \x01(\v2$.oll.protocol.CommitDocumentsRequestH\x00R\x0fcommitDocuments\x12?\n" +
	"\n" +
	"get_config\x18\x06 \x01(\v2\x1e.oll.protocol.GetConfigRequestH\x00R\tgetConfig\x12a\n" +
	"\x16invoke_config_function\x18\a \x01(\v2).oll.protocol.InvokeConfigFunctionRequestH\x00R\x14invokeConfigFunctionB\x06\n" +
	"\x04call\"\xfb\x04\n" +
	"\x10HostCallResponse\x12I\n" +
	"\rread_document\x18\x01 \x01(\v2\".oll.protocol.ReadDocumentResponseH\x00R\freadDocument\x12L\n" +
	"\x0elist_directory\x18\x02 \x01(\v2#.oll.protocol.ListDirectoryResponseH\x00R\rlistDirectory\x12V\n" +
	"\x12get_directory_tree\x18\x03 \x01(\v2&.oll.protocol.GetDirectoryTreeResponseH\x00R\x10getDirectoryTree\x12=\n" +
	"\tread_crdt\x18\x04 \x01(\v2\x1e.oll.protocol.ReadCrdtResponseH\x00R\breadCrdt\x12R\n" +
	"\x10commit_documents\x18\x05 \x01(\v2%.oll.protocol.CommitDocumentsResponseH\x00R\x0fcommitDocuments\x12@\n" +
	"\n" +
	"get_config\x18\x06 \x01(\v2\x1f.oll.protocol.GetConfigResponseH\x00R\tgetConfig\x12b\n" +
	"\x16invoke_config_function\x18\a \x01(\v2*.oll.protocol.InvokeConfigFunctionResponseH\x00R\x14invokeConfigFunction\x123\n" +
	"\x05error\x18\x0f \x01(\v2\x1b.oll.protocol.ProtocolErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\xb8\x02\n" +
	"\tLogRecord\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\x05level\x18\x02 \x01(\x0e2\x16.oll.protocol.LogLevelR\x05level\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12;\n" +
	"\x06fields\x18\x05 \x03(\v2#.oll.protocol.LogRecord.FieldsEntryR\x06fields\x1aT\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.oll.protocol.ConfigValueR\x05value:\x028\x01\"!\n" +
	"\tHeartbeat\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"y\n" +
	"\x0fShutdownRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12N\n" +
	"\x15grace_period_deadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x13gracePeriodDeadline\"\x16\n" +
	"\x14ShutdownAcknowledged\"\xc4\f\n" +
	"\x0ePluginEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x04R\tmessageId\x12\x1e\n" +
	"\breply_to\x18\x02 \x01(\x04H\x01R\areplyTo\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12,\n" +
	"\x12plugin_instance_id\x18\x04 \x01(\tR\x10pluginInstanceId\x120\n" +
	"\x05trace\x18\x05 \x01(\v2\x1a.oll.protocol.TraceContextR\x05trace\x128\n" +
	"\n" +
	"host_hello\x18\n" +
	" \x01(\v2\x17.oll.protocol.HostHelloH\x00R\thostHello\x12>\n" +
	"\fplugin_hello\x18\v \x01(\v2\x19.oll.protocol.PluginHelloH\x00R\vpluginHello\x122\n" +
	"\x05ready\x18\f \x01(\v2\x1a.oll.protocol.SessionReadyH\x00R\x05ready\x12<\n" +
	"\tstart_job\x18\r \x01(\v2\x1d.oll.protocol.StartJobRequestH\x00R\bstartJob\x12>\n" +
	"\fjob_accepted\x18\x0e \x01(\v2\x19.oll.protocol.JobAcceptedH\x00R\vjobAccepted\x128\n" +
	"\n" +
	"job_update\x18\x0f \x01(\v2\x17.oll.protocol.JobUpdateH\x00R\tjobUpdate\x12<\n" +
	"\thost_call\x18\x10 \x01(\v2\x1d.oll.protocol.HostCallRequestH\x00R\bhostCall\x12A\n" +
	"\vhost_result\x18\x11 \x01(\v2\x1e.oll.protocol.HostCallResponseH\x00R\n" +
	"hostResult\x12+\n" +
	"\x03log\x18\x12 \x01(\v2\x17.oll.protocol.LogRecordH\x00R\x03log\x127\n" +
	"\theartbeat\x18\x13 \x01(\v2\x17.oll.protocol.HeartbeatH\x00R\theartbeat\x12;\n" +
	"\bshutdown\x18\x14 \x01(\v2\x1d.oll.protocol.ShutdownRequestH\x00R\bshutdown\x12Y\n" +
	"\x15shutdown_acknowledged\x18\x15 \x01(\v2\".oll.protocol.ShutdownAcknowledgedH\x00R\x14shutdownAcknowledged\x12D\n" +
	"\x0eprotocol_error\x18\x16 \x01(\v2\x1b.oll.protocol.ProtocolErrorH\x00R\rprotocolError\x12L\n" +
	"\x0eartifact_start\x18\x17 \x01(\v2#.oll.protocol.ArtifactTransferStartH\x00R\rartifactStart\x12U\n" +
	"\x11artifact_accepted\x18\x18 \x01(\v2&.oll.protocol.ArtifactTransferAcceptedH\x00R\x10artifactAccepted\x12L\n" +
	"\x0eartifact_chunk\x18\x19 \x01(\v2#.oll.protocol.ArtifactTransferChunkH\x00R\rartifactChunk\x12U\n" +
	"\x11artifact_complete\x18\x1a \x01(\v2&.oll.protocol.ArtifactTransferCompleteH\x00R\x10artifactComplete\x12G\n" +
	"\x0fartifact_stored\x18\x1b \x01(\v2\x1c.oll.protocol.ArtifactStoredH\x00R\x0eartifactStored\x12?\n" +
	"\n" +
	"cancel_job\x18\x1c \x01(\v2\x1e.oll.protocol.CancelJobRequestH\x00R\tcancelJob\x12]\n" +
	"\x17cancel_job_acknowledged\x18\x1d \x01(\v2#.oll.protocol.CancelJobAcknowledgedH\x00R\x15cancelJobAcknowledgedB\t\n" +
	"\apayloadB\v\n" +
	"\t_reply_to*k\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x01\x12\x17\n" +
	"\x13JOB_STATE_SUCCEEDED\x10\x02\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x03*\x90\x01\n" +
	"\x15JobCancellationReason\x12'\n" +
	"#JOB_CANCELLATION_REASON_UNSPECIFIED\x10\x00\x12(\n" +
	"$JOB_CANCELLATION_REASON_USER_REQUEST\x10\x01\x12$\n" +
	" JOB_CANCELLATION_REASON_DEADLINE\x10\x022Z\n" +
	"\rPluginRuntime\x12I\n" +
	"\aConnect\x12\x1c.oll.protocol.PluginEnvelope\x1a\x1c.oll.protocol.PluginEnvelope(\x010\x01b\x06proto3"

var (
	file_oll_plugin_proto_rawDescOnce sync.Once
	file_oll_plugin_proto_rawDescData []byte
)

func file_oll_plugin_proto_rawDescGZIP() []byte {
	file_oll_plugin_proto_rawDescOnce.Do(func() {
		file_oll_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oll_plugin_proto_rawDesc), len(file_oll_plugin_proto_rawDesc)))
	})
	return file_oll_plugin_proto_rawDescData
}

var file_oll_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_oll_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_oll_plugin_proto_goTypes = []any{
	(JobState)(0),                        // 0: oll.protocol.JobState
	(JobCancellationReason)(0),           // 1: oll.protocol.JobCancellationReason
	(*HostHello)(nil),                    // 2: oll.protocol.HostHello
	(*ActionDescriptor)(nil),             // 3: oll.protocol.ActionDescriptor
	(*PluginHello)(nil),                  // 4: oll.protocol.PluginHello
	(*SessionReady)(nil),                 // 5: oll.protocol.SessionReady
	(*ActionInvocation)(nil),             // 6: oll.protocol.ActionInvocation
	(*StartJobRequest)(nil),              // 7: oll.protocol.StartJobRequest
	(*JobAccepted)(nil),                  // 8: oll.protocol.JobAccepted
	(*JobUpdate)(nil),                    // 9: oll.protocol.JobUpdate
	(*ArtifactDescriptor)(nil),           // 10: oll.protocol.ArtifactDescriptor
	(*ArtifactTransferStart)(nil),        // 11: oll.protocol.ArtifactTransferStart
	(*ArtifactTransferAccepted)(nil),     // 12: oll.protocol.ArtifactTransferAccepted
	(*ArtifactTransferChunk)(nil),        // 13: oll.protocol.ArtifactTransferChunk
	(*ArtifactTransferComplete)(nil),     // 14: oll.protocol.ArtifactTransferComplete
	(*ArtifactStored)(nil),               // 15: oll.protocol.ArtifactStored
	(*CancelJobRequest)(nil),             // 16: oll.protocol.CancelJobRequest
	(*CancelJobAcknowledged)(nil),        // 17: oll.protocol.CancelJobAcknowledged
	(*HostCallRequest)(nil),              // 18: oll.protocol.HostCallRequest
	(*HostCallResponse)(nil),             // 19: oll.protocol.HostCallResponse
	(*LogRecord)(nil),                    // 20: oll.protocol.LogRecord
	(*Heartbeat)(nil),                    // 21: oll.protocol.Heartbeat
	(*ShutdownRequest)(nil),              // 22: oll.protocol.ShutdownRequest
	(*ShutdownAcknowledged)(nil),         // 23: oll.protocol.ShutdownAcknowledged
	(*PluginEnvelope)(nil),               // 24: oll.protocol.PluginEnvelope
	nil,                                  // 25: oll.protocol.LogRecord.FieldsEntry
	(*NodeIdentity)(nil),                 // 26: oll.protocol.NodeIdentity
	(*PluginId)(nil),                     // 27: oll.protocol.PluginId
	(*PluginName)(nil),                   // 28: oll.protocol.PluginName
	(*PluginJobId)(nil),                  // 29: oll.protocol.PluginJobId
	(*timestamppb.Timestamp)(nil),        // 30: google.protobuf.Timestamp
	(*ConfigValue)(nil),                  // 31: oll.protocol.ConfigValue
	(*ProtocolError)(nil),                // 32: oll.protocol.ProtocolError
	(*PluginArtifactId)(nil),             // 33: oll.protocol.PluginArtifactId
	(*ReadDocumentRequest)(nil),          // 34: oll.protocol.ReadDocumentRequest
	(*ListDirectoryRequest)(nil),         // 35: oll.protocol.ListDirectoryRequest
	(*GetDirectoryTreeRequest)(nil),      // 36: oll.protocol.GetDirectoryTreeRequest
	(*ReadCrdtRequest)(nil),              // 37: oll.protocol.ReadCrdtRequest
	(*CommitDocumentsRequest)(nil),       // 38: oll.protocol.CommitDocumentsRequest
	(*GetConfigRequest)(nil),             // 39: oll.protocol.GetConfigRequest
	(*InvokeConfigFunctionRequest)(nil),  // 40: oll.protocol.InvokeConfigFunctionRequest
	(*ReadDocumentResponse)(nil),         // 41: oll.protocol.ReadDocumentResponse
	(*ListDirectoryResponse)(nil),        // 42: oll.protocol.ListDirectoryResponse
	(*GetDirectoryTreeResponse)(nil),     // 43: oll.protocol.GetDirectoryTreeResponse
	(*ReadCrdtResponse)(nil),             // 44: oll.protocol.ReadCrdtResponse
	(*CommitDocumentsResponse)(nil),      // 45: oll.protocol.CommitDocumentsResponse
	(*GetConfigResponse)(nil),            // 46: oll.protocol.GetConfigResponse
	(*InvokeConfigFunctionResponse)(nil), // 47: oll.protocol.InvokeConfigFunctionResponse
	(LogLevel)(0),                        // 48: oll.protocol.LogLevel
	(*TraceContext)(nil),                 // 49: oll.protocol.TraceContext
}
var file_oll_plugin_proto_depIdxs = []int32{
	26, // 0: oll.protocol.HostHello.node:type_name -> oll.protocol.NodeIdentity
	27, // 1: oll.protocol.HostHello.plugin_id:type_name -> oll.protocol.PluginId
	28, // 2: oll.protocol.HostHello.plugin_name:type_name -> oll.protocol.PluginName
	27, // 3: oll.protocol.PluginHello.plugin_id:type_name -> oll.protocol.PluginId
	28, // 4: oll.protocol.PluginHello.plugin_name:type_name -> oll.protocol.PluginName
	3,  // 5: oll.protocol.PluginHello.actions:type_name -> oll.protocol.ActionDescriptor
	29, // 6: oll.protocol.StartJobRequest.job_id:type_name -> oll.protocol.PluginJobId
	30, // 7: oll.protocol.StartJobRequest.deadline:type_name -> google.protobuf.Timestamp
	6,  // 8: oll.protocol.StartJobRequest.action:type_name -> oll.protocol.ActionInvocation
	29, // 9: oll.protocol.JobAccepted.job_id:type_name -> oll.protocol.PluginJobId
	29, // 10: oll.protocol.JobUpdate.job_id:type_name -> oll.protocol.PluginJobId
	0,  // 11: oll.protocol.JobUpdate.state:type_name -> oll.protocol.JobState
	31, // 12: oll.protocol.JobUpdate.result:type_name -> oll.protocol.ConfigValue
	32, // 13: oll.protocol.JobUpdate.error:type_name -> oll.protocol.ProtocolError
	10, // 14: oll.protocol.JobUpdate.artifacts:type_name -> oll.protocol.ArtifactDescriptor
	33, // 15: oll.protocol.ArtifactDescriptor.artifact_id:type_name -> oll.protocol.PluginArtifactId
	29, // 16: oll.protocol.ArtifactTransferStart.job_id:type_name -> oll.protocol.PluginJobId
	10, // 17: oll.protocol.ArtifactTransferStart.artifact:type_name -> oll.protocol.ArtifactDescriptor
	33, // 18: oll.protocol.ArtifactTransferAccepted.artifact_id:type_name -> oll.protocol.PluginArtifactId
	33, // 19: oll.protocol.ArtifactTransferChunk.artifact_id:type_name -> oll.protocol.PluginArtifactId
	33, // 20: oll.protocol.ArtifactTransferComplete.artifact_id:type_name -> oll.protocol.PluginArtifactId
	33, // 21: oll.protocol.ArtifactStored.artifact_id:type_name -> oll.protocol.PluginArtifactId
	29, // 22: oll.protocol.CancelJobRequest.job_id:type_name -> oll.protocol.PluginJobId
	1,  // 23: oll.protocol.CancelJobRequest.reason:type_name -> oll.protocol.JobCancellationReason
	29, // 24: oll.protocol.CancelJobAcknowledged.job_id:type_name -> oll.protocol.PluginJobId
	34, // 25: oll.protocol.HostCallRequest.read_document:type_name -> oll.protocol.ReadDocumentRequest
	35, // 26: oll.protocol.HostCallRequest.list_directory:type_name -> oll.protocol.ListDirectoryRequest
	36, // 27: oll.protocol.HostCallRequest.get_directory_tree:type_name -> oll.protocol.GetDirectoryTreeRequest
	37, // 28: oll.protocol.HostCallRequest.read_crdt:type_name -> oll.protocol.ReadCrdtRequest
	38, // 29: oll.protocol.HostCallRequest.commit_documents:type_name -> oll.protocol.CommitDocumentsRequest
	39, // 30: oll.protocol.HostCallRequest.get_config:type_name -> oll.protocol.GetConfigRequest
	40, // 31: oll.protocol.HostCallRequest.invoke_config_function:type_name -> oll.protocol.InvokeConfigFunctionRequest
	41, // 32: oll.protocol.HostCallResponse.read_document:type_name -> oll.protocol.ReadDocumentResponse
	42, // 33: oll.protocol.HostCallResponse.list_directory:type_name -> oll.protocol.ListDirectoryResponse
	43, // 34: oll.protocol.HostCallResponse.get_directory_tree:type_name -> oll.protocol.GetDirectoryTreeResponse
	44, // 35: oll.protocol.HostCallResponse.read_crdt:type_name -> oll.protocol.ReadCrdtResponse
	45, // 36: oll.protocol.HostCallResponse.commit_documents:type_name -> oll.protocol.CommitDocumentsResponse
	46, // 37: oll.protocol.HostCallResponse.get_config:type_name -> oll.protocol.GetConfigResponse
	47, // 38: oll.protocol.HostCallResponse.invoke_config_function:type_name -> oll.protocol.InvokeConfigFunctionResponse
	32, // 39: oll.protocol.HostCallResponse.error:type_name -> oll.protocol.ProtocolError
	30, // 40: oll.protocol.LogRecord.timestamp:type_name -> google.protobuf.Timestamp
	48, // 41: oll.protocol.LogRecord.level:type_name -> oll.protocol.LogLevel
	25, // 42: oll.protocol.LogRecord.fields:type_name -> oll.protocol.LogRecord.FieldsEntry
	30, // 43: oll.protocol.ShutdownRequest.grace_period_deadline:type_name -> google.protobuf.Timestamp
	49, // 44: oll.protocol.PluginEnvelope.trace:type_name -> oll.protocol.TraceContext
	2,  // 45: oll.protocol.PluginEnvelope.host_hello:type_name -> oll.protocol.HostHello
	4,  // 46: oll.protocol.PluginEnvelope.plugin_hello:type_name -> oll.protocol.PluginHello
	5,  // 47: oll.protocol.PluginEnvelope.ready:type_name -> oll.protocol.SessionReady
	7,  // 48: oll.protocol.PluginEnvelope.start_job:type_name -> oll.protocol.StartJobRequest
	8,  // 49: oll.protocol.PluginEnvelope.job_accepted:type_name -> oll.protocol.JobAccepted
	9,  // 50: oll.protocol.PluginEnvelope.job_update:type_name -> oll.protocol.JobUpdate
	18, // 51: oll.protocol.PluginEnvelope.host_call:type_name -> oll.protocol.HostCallRequest
	19, // 52: oll.protocol.PluginEnvelope.host_result:type_name -> oll.protocol.HostCallResponse
	20, // 53: oll.protocol.PluginEnvelope.log:type_name -> oll.protocol.LogRecord
	21, // 54: oll.protocol.PluginEnvelope.heartbeat:type_name -> oll.protocol.Heartbeat
	22, // 55: oll.protocol.PluginEnvelope.shutdown:type_name -> oll.protocol.ShutdownRequest
	23, // 56: oll.protocol.PluginEnvelope.shutdown_acknowledged:type_name -> oll.protocol.ShutdownAcknowledged
	32, // 57: oll.protocol.PluginEnvelope.protocol_error:type_name -> oll.protocol.ProtocolError
	11, // 58: oll.protocol.PluginEnvelope.artifact_start:type_name -> oll.protocol.ArtifactTransferStart
	12, // 59: oll.protocol.PluginEnvelope.artifact_accepted:type_name -> oll.protocol.ArtifactTransferAccepted
	13, // 60: oll.protocol.PluginEnvelope.artifact_chunk:type_name -> oll.protocol.ArtifactTransferChunk
	14, // 61: oll.protocol.PluginEnvelope.artifact_complete:type_name -> oll.protocol.ArtifactTransferComplete
	15, // 62: oll.protocol.PluginEnvelope.artifact_stored:type_name -> oll.protocol.ArtifactStored
	16, // 63: oll.protocol.PluginEnvelope.cancel_job:type_name -> oll.protocol.CancelJobRequest
	17, // 64: oll.protocol.PluginEnvelope.cancel_job_acknowledged:type_name -> oll.protocol.CancelJobAcknowledged
	31, // 65: oll.protocol.LogRecord.FieldsEntry.value:type_name -> oll.protocol.ConfigValue
	24, // 66: oll.protocol.PluginRuntime.Connect:input_type -> oll.protocol.PluginEnvelope
	24, // 67: oll.protocol.PluginRuntime.Connect:output_type -> oll.protocol.PluginEnvelope
	67, // [67:68] is the sub-list for method output_type
	66, // [66:67] is the sub-list for method input_type
	66, // [66:66] is the sub-list for extension type_name
	66, // [66:66] is the sub-list for extension extendee
	0,  // [0:66] is the sub-list for field type_name
}

func init() { file_oll_plugin_proto_init() }
func file_oll_plugin_proto_init() {
	if File_oll_plugin_proto != nil {
		return
	}
	file_oll_common_proto_init()
	file_oll_config_proto_init()
	file_oll_document_proto_init()
	file_oll_plugin_proto_msgTypes[5].OneofWrappers = []any{
		(*StartJobRequest_Action)(nil),
	}
	file_oll_plugin_proto_msgTypes[7].OneofWrappers = []any{}
	file_oll_plugin_proto_msgTypes[16].OneofWrappers = []any{
		(*HostCallRequest_ReadDocument)(nil),
		(*HostCallRequest_ListDirectory)(nil),
		(*HostCallRequest_GetDirectoryTree)(nil),
		(*HostCallRequest_ReadCrdt)(nil),
		(*HostCallRequest_CommitDocuments)(nil),
		(*HostCallRequest_GetConfig)(nil),
		(*HostCallRequest_InvokeConfigFunction)(nil),
	}
	file_oll_plugin_proto_msgTypes[17].OneofWrappers = []any{
		(*HostCallResponse_ReadDocument)(nil),
		(*HostCallResponse_ListDirectory)(nil),
		(*HostCallResponse_GetDirectoryTree)(nil),
		(*HostCallResponse_ReadCrdt)(nil),
		(*HostCallResponse_CommitDocuments)(nil),
		(*HostCallResponse_GetConfig)(nil),
		(*HostCallResponse_InvokeConfigFunction)(nil),
		(*HostCallResponse_Error)(nil),
	}
	file_oll_plugin_proto_msgTypes[22].OneofWrappers = []any{
		(*PluginEnvelope_HostHello)(nil),
		(*PluginEnvelope_PluginHello)(nil),
		(*PluginEnvelope_Ready)(nil),
		(*PluginEnvelope_StartJob)(nil),
		(*PluginEnvelope_JobAccepted)(nil),
		(*PluginEnvelope_JobUpdate)(nil),
		(*PluginEnvelope_HostCall)(nil),
		(*PluginEnvelope_HostResult)(nil),
		(*PluginEnvelope_Log)(nil),
		(*PluginEnvelope_Heartbeat)(nil),
		(*PluginEnvelope_Shutdown)(nil),
		(*PluginEnvelope_ShutdownAcknowledged)(nil),
		(*PluginEnvelope_ProtocolError)(nil),
		(*PluginEnvelope_ArtifactStart)(nil),
		(*PluginEnvelope_ArtifactAccepted)(nil),
		(*PluginEnvelope_ArtifactChunk)(nil),
		(*PluginEnvelope_ArtifactComplete)(nil),
		(*PluginEnvelope_ArtifactStored)(nil),
		(*PluginEnvelope_CancelJob)(nil),
		(*PluginEnvelope_CancelJobAcknowledged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oll_plugin_proto_rawDesc), len(file_oll_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oll_plugin_proto_goTypes,
		DependencyIndexes: file_oll_plugin_proto_depIdxs,
		EnumInfos:         file_oll_plugin_proto_enumTypes,
		MessageInfos:      file_oll_plugin_proto_msgTypes,
	}.Build()
	File_oll_plugin_proto = out.File
	file_oll_plugin_proto_goTypes = nil
	file_oll_plugin_proto_depIdxs = nil
}
