// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: oll/plugin.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginRuntime_Connect_FullMethodName = "/oll.protocol.PluginRuntime/Connect"
)

// PluginRuntimeClient is the client API for PluginRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// oll hosts this service on an instance-owned loopback listener. The spawned
// plugin receives OLL_PLUGIN_ENDPOINT, connects as the gRPC client, and all
// calls in either direction share this one stream.
type PluginRuntimeClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginEnvelope, PluginEnvelope], error)
}

type pluginRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginRuntimeClient(cc grpc.ClientConnInterface) PluginRuntimeClient {
	return &pluginRuntimeClient{cc}
}

func (c *pluginRuntimeClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginEnvelope, PluginEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginRuntime_ServiceDesc.Streams[0], PluginRuntime_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PluginEnvelope, PluginEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginRuntime_ConnectClient = grpc.BidiStreamingClient[PluginEnvelope, PluginEnvelope]

// PluginRuntimeServer is the server API for PluginRuntime service.
// All implementations must embed UnimplementedPluginRuntimeServer
// for forward compatibility.
//
// oll hosts this service on an instance-owned loopback listener. The spawned
// plugin receives OLL_PLUGIN_ENDPOINT, connects as the gRPC client, and all
// calls in either direction share this one stream.
type PluginRuntimeServer interface {
	Connect(grpc.BidiStreamingServer[PluginEnvelope, PluginEnvelope]) error
	mustEmbedUnimplementedPluginRuntimeServer()
}

// UnimplementedPluginRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginRuntimeServer struct{}

func (UnimplementedPluginRuntimeServer) Connect(grpc.BidiStreamingServer[PluginEnvelope, PluginEnvelope]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPluginRuntimeServer) mustEmbedUnimplementedPluginRuntimeServer() {}
func (UnimplementedPluginRuntimeServer) testEmbeddedByValue()                       {}

// UnsafePluginRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginRuntimeServer will
// result in compilation errors.
type UnsafePluginRuntimeServer interface {
	mustEmbedUnimplementedPluginRuntimeServer()
}

func RegisterPluginRuntimeServer(s grpc.ServiceRegistrar, srv PluginRuntimeServer) {
	// If the following call pancis, it indicates UnimplementedPluginRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginRuntime_ServiceDesc, srv)
}

func _PluginRuntime_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginRuntimeServer).Connect(&grpc.GenericServerStream[PluginEnvelope, PluginEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginRuntime_ConnectServer = grpc.BidiStreamingServer[PluginEnvelope, PluginEnvelope]

// PluginRuntime_ServiceDesc is the grpc.ServiceDesc for PluginRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oll.protocol.PluginRuntime",
	HandlerType: (*PluginRuntimeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _PluginRuntime_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "oll/plugin.proto",
}
